### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by molke-productions**
Some minor clean-up for the Qt Charts version.

### CODE REVIEW

**Comment by be1** [comment]
> @molke-productions you're right. Octave output would be too far. I've just pushed removing of the octave button, letting the code underneath for reference...

Maybe it is useless to keep ocatve output generation code. I suggest to remove that part of hidden code.

**Comment by molke-productions** [comment]
Sorry for the delay. That part should already be removed in the pull request. If you find some time to check that this modified version of your additions still works as expected, then I will go ahead and try to merge this into the master branch.

**Comment by be1** [comment]
Thanks molke, sorry for the loong delay. You could merge safely by yourself.

**Comment by be1** [comment]
Should we make a tag for this version ?

**Comment by molke-productions** [comment]
Thanks for checking and merging.
As far as I can tell, there seems to be no new functionality or major redesign, so maybe a minor version step like 1.4.1?

**Comment by be1** [comment]
Yes, I think 1.4.1 is a good tag.

**Comment by molke-productions** [comment]
Sure, I agree.

**Pull request merged**
