### PR TITLE
Qtcharts implementation

### PR DESCRIPTION
**Pull request by be1**
Hello,
I implemented a **QtCharts** version here. No more dependency to **Qwt**.
If you wish to use it, can you consider my pull request ?
Thanks,
 Benoît

### CODE REVIEW

**Comment by be1** [comment]
This branch also includes printing which is a nice feature.

**Comment by gaydenko** [comment]
It is really very intriguing addition, especially for me as initial creator :) Hope @molke-productions  will find a weekend hour to evaluate and probably merge this new QLoud incarnation!

**Comment by molke-productions** [comment]
Sorry for the delay. I’m still trying to understand GitHub, but I should be notified now without being explicitly mentioned.
@be1 Your alternative implementation seems to be working just fine. Thank you very much. Since you seem to be much more capable with Qt than me, I can also give you direct write access to this repository? 

I tried merging your pull request into a new qtcharts branch for now. If there are no reservations, this can also become the master branch (maybe as a new major version).

The only thing I did change (apart from some code formatting) are tick mark/axis settings to get 20 dB divisions in SPL and harmonics plots.

I have two suggestions which are above my abilities. 
First, zooming in y-direction does not seem to work on my system with the new implementation. Is this a restriction of Qt Charts?
Second, I would prefer to have the new print button not spanning the whole window width. This might prevent accidentally clicking on it. To maximize the plot area, it might be even better to move it to the top row (exists only on the SPL tab)?

**Comment by be1** [comment]
@molke-productions Glad you like my proposition.
Yes, I will modify the print button size, you are right.
I will try to know how to zoom on the y-axis in QtCharts.
If you want to give me write access to your repo, this is ok for me. I'll first use your qtchart branch.

**Comment by be1** [comment]
Couldn't find an easy way to both zoom in x-axis AND y-axis in QtChart.Sorry.
I may investigate more later for subclassing QChartView and implement that kind of zoom myself.

**Comment by molke-productions** [comment]
No worries. One less dependency is well worth it. But maybe this should be resolved before declaring it the new master branch. 
Actually, I tend to do plots externally (GNU Octave) if I want more fine-grained control. In this regard, for me, an ASCII export of the plotted data would be more useful than direct printing, so I don’t have to deal with the audio files again.

**Comment by be1** [comment]
Thanks, I will work in the qtcharts branch. The idea of exporting ASCII is a good idea. I only know Gnuplot. If you have any GNU Octave import example I would be glad if you could send me an example by attachment here. Thanks !

**Comment by molke-productions** [comment]
Attached is a simple example (rename `qloudplot.m.txt` to `.m`). Some constants (`path`, `key`, …) have to be manually adjusted for your setup. This is a reduced version of a slightly more elaborate comparison between different simulations and the measured response of a crossover (`loudspeaker.pdf`), and it plots just the magnitude response (my signal processing courses were a long time ago).

[loudspeaker.pdf](https://github.com/molke-productions/qloud/files/5470968/loudspeaker.pdf)
[qloudplot.m.txt](https://github.com/molke-productions/qloud/files/5470970/qloudplot.m.txt)

**Comment by molke-productions** [comment]
As for the zoom, maybe it is easier to bind the directions to different events – like left click to x-axis and right click to y-axis (double-click for reset)?

**Comment by be1** [comment]
Hello. So I switched to your repository, branch qcharts. I made some new features on it, including GNU octave output for SPL plot only. As I don't know octave, could you implement octave output for the other tabs ? If you wan to...
I'm closing this ticket now.

**Comment by be1** [comment]
I could find, by reading the docs, an easy way to zoom in with a rectangular selection :-)

**Pull request closed without merging**
